### PR TITLE
VisitHttp*Headers methods signatures changed

### PR DESCRIPTION
**Pull request by QABuildTeam**
### Summary

Introduce a convenient way to access the JsonRpcRequest/Response body while using VisitHttp[Request/Response]Headers methods. It may be useful for creating/verifying a signature HTTP header based on request/response content.

### Changes

JsonRpcClient.VisitHttpRequestHeaders and JsonRpcClient.VisitHttpResponseHeaders methods signatures change: an HttpContent parameter is added which defaults to null (for downwards compatibility).

### Outcome

JsonRpcClient class has no changes in behaviour, benchmarks, or testing. The behaviour may be changed in overloaded classes.

### Additional Information

Slight changes in the order of JsonRpcRequest body creation statements - the body should be available before a call to PrepareHttpHeaders.

### CODE REVIEW

**Comment by alexanderkozlenko** [comment]
Hi @QABuildTeam! Thank you for contributing to a project. Could you please provide some source code with an example of new feature usage scenarios?

**Comment by QABuildTeam** [comment]
> 
> 
> Hi @QABuildTeam! Thank you for contributing to a project. Could you please provide some source code with an example of new feature usage scenarios?

Hi @alexanderkozlenko Thank you for reviewing my commits. I have added some code into README.md file, hope it helps.

**Comment by alexanderkozlenko** [comment]
I presume the required functionality requires API changes in the library. Could you please look into the PR https://github.com/alexanderkozlenko/json-rpc-client/pull/21 and tell if the implemented approach will work for you? There is also a new unit test with an example of required functionality usage.

**Comment by QABuildTeam** [comment]
> 
> 
> I presume the requested functionality requires breaking API changes in the library. Could you please look into the PR #21 and tell if the implemented approach will work for you? There is also a new unit test with an example of required functionality usage.

Yes, this is exactly what I intended to implement. I introduced an HttpContent parameter in a pursuit not to ruin existing applications out there (probably people have already used VisitHttp*Headers overrides). But yes, PR #22 changes are ok. Thank you.

P. S. Maybe it could be useful to add #if NETCOREAPP2_2 checks to the code, if targeting to netcoreapp2.2.

**Comment by alexanderkozlenko** [comment]
Unfortunately, in this case, there will be breaking changes in API to keep it consistent. There is no reason to add explicit .NET Core 2.2 support in the package (.NET Core 2.1 assembly will be used for .NET Core 2.1 and higher projects). The PR is already merged and can be tested with a MyGet package  [Anemonis.JsonRpc.ServiceClient 1.14.0-beta-20190614.2](https://www.myget.org/feed/alexanderkozlenko/package/nuget/Anemonis.JsonRpc.ServiceClient/1.14.0-beta-20190614.2). If it works for you, you can safely close this PR. Thank you for contribution!

**Comment by QABuildTeam** [comment]
> 
> 
> Unfortunately, in this case, there will be breaking changes in API to keep it consistent. There is no reason to add explicit .NET Core 2.2 support in the package (.NET Core 2.1 assembly will be used for .NET Core 2.1 and higher projects). The PR is already merged and can be tested with a MyGet package [Anemonis.JsonRpc.ServiceClient 1.14.0-beta-20190614.2](https://www.myget.org/feed/alexanderkozlenko/package/nuget/Anemonis.JsonRpc.ServiceClient/1.14.0-beta-20190614.2). If it works for you, you can safely close this PR. Thank you for contribution!

@alexanderkozlenko Yes, it worked, except for a need to explicitly add the url to nuget sources. Hope the changes will soon go to the main branch so that I can use the package as a regular one. Thank you very much and keep up good work!

**Pull request closed without merging**
